### ISSUE TITLE
Can't update Artist's value in Library's playlist

### ISSUE THREAD

**Issue by bepriyansh** [m7kra/Musicly#1]
On ubuntu 24.04 LTS, When you try to change the Title of of any Playlist in the Library, Artist also change and you can't change Artist from Artist input box.

**Comment by bepriyansh** [comment]
i read your code, looks like you fixed the bug but it's not in production for linux users.

**Comment by bogosorter** [comment]
Hi there! Thanks for reaching out. You nailed it ;)

I discovered that bug a while ago and fixed it (and a couple of other things too). My plan was to release a patch version after some testing. To be honest, I've been dragging that release for a while now and kind of forgot about it. I'll try to have it live by the end of the week. Feel free to ping me if I don't follow through on my promise.

If you really need that working in the meantime, you can also build it from source ([this](https://bogosorter.github.io/Musicly/docs/dev) may be useful if you need some help).

**Comment by bogosorter** [comment]
Hi there! I just released a new Musicly version that should fix this issue (see [this](https://github.com/bogosorter/Musicly/releases/tag/v0.5.0)).

Thanks for pushing me to do it and feel free to reach out if you have any other issues.
